$urls = @(
    "https://lookuptax.com/docs/pt/explicadores/vies-intrastat-guia",
    "https://lookuptax.com/docs/zh-Hans/numero-identificacion-fiscal/guia-rut-uruguay",
    "https://lookuptax.com/docs/zh-Hans/shuiwu-shibie-haoma/yinni-shuihao",
    "https://lookuptax.com/docs/de/tax-identification-number/Argentina-tax-id-guide",
    "https://lookuptax.com/docs/de/how-to-verify/gst-verification-canada",
    "https://lookuptax.com/docs/zh-Hans/jieshipage/nixiang-zhengshou-jizhi-iva",
    "https://lookuptax.com/docs/pt/numero-identificacion-fiscal/guia-rut-uruguay",
    "https://lookuptax.com/docs/es/tax-identification-number/morocco-tax-id-guide",
    "https://lookuptax.com/docs/pt/how-to-verify/gst-verification-canada",
    "https://lookuptax.com/docs/zh-Hans/tags/indonesia",
    "https://lookuptax.com/docs/de/tax-identification-number/andorra-tax-id-guide",
    "https://lookuptax.com/docs/zh-Hans/vat/germany",
    "https://lookuptax.com/docs/pt/how-to-verify/dni-verification-argentina",
    "https://lookuptax.com/docs/es/tags/abn",
    "https://lookuptax.com/docs/de/wie-man-ueberprueft/eu-mehrwertsteuer-vies",
    "https://lookuptax.com/docs/einvoicing-status-networks",
    "https://lookuptax.com/docs/de/tax-identification-number/venezuela-tax-id-guide",
    "https://lookuptax.com/docs/tax-identification-number/moldova-tax-id-guide",
    "https://lookuptax.com/docs/es/tags/vietnam",
    "https://lookuptax.com/docs/pt/tax-identification-number/isle-of-man-tax-id-guide",
    "https://lookuptax.com/docs/zh-Hans/shuiwu-shibie-haoma/riben-shuihao",
    "https://lookuptax.com/docs/ruhe-yanzheng/yindu-gstin",
    "https://lookuptax.com/docs/pt/umsatzsteuer-identifikationsnummer-pruefen",
    "https://lookuptax.com/docs/es/contact-us",
    "https://lookuptax.com/docs/pt/how-to-verify/curp-verification-mexico",
    "https://lookuptax.com/docs/es/tax-identification-number/maldives-tax-id-guide",
    "https://lookuptax.com/docs/de/tax-identification-number/gibraltar-tax-id-guide",
    "https://lookuptax.com/docs/es/tax-identification-number/colombia-tax-id-guide",
    "https://lookuptax.com/docs/pt/tax-identification-number/romania-tax-id-guide",
    "https://lookuptax.com/docs/de/numero-identificacion-fiscal/guia-cuit-argentina",
    "https://lookuptax.com/docs/zh-Hans/explainers/learn-about-soc2-compliance",
    "https://lookuptax.com/docs/pt/tax-identification-number/colombia-tax-id-guide",
    "https://lookuptax.com/docs/de/how-to-verify/vat-number-bulgaria",
    "https://lookuptax.com/docs/es/how-to-verify/eori-verification-eu-vies",
    "https://lookuptax.com/docs/zh-Hans/how-to-verify/cr-verification-qatar",
    "https://lookuptax.com/docs/de/how-to-verify/curp-verification-mexico",
    "https://lookuptax.com/docs/sales-tax/texas",
    "https://lookuptax.com/docs/pt/how-to-verify/vat-verification-south-africa",
    "https://lookuptax.com/docs/de/tax-identification-number/Australia-tax-id-guide",
    "https://lookuptax.com/docs/de/tags/rcm",
    "https://lookuptax.com/docs/es/how-to-verify/cr-verification-qatar",
    "https://lookuptax.com/docs/how-to-verify/registration-number-malaysia",
    "https://lookuptax.com/docs/zh-Hans/tax-identification-number/canada-tax-id-guide",
    "https://lookuptax.com/docs/pt/how-to-verify/tin-verification-azerbaijan",
    "https://lookuptax.com/docs/es/tax-identification-number/dominica-tax-id-guide",
    "https://lookuptax.com/docs/de/explainers/explaining-OIDAR-services-and-GST-Compliance-for-Suppliers-in-India",
    "https://lookuptax.com/docs/pt/tax-identification-number/andorra-tax-id-guide",
    "https://lookuptax.com/docs/pt/tax-identification-number/kuwait-tax-id-guide",
    "https://lookuptax.com/docs/es/tax-identification-number/gibraltar-tax-id-guide",
    "https://lookuptax.com/docs/es/tax-identification-number/portugal-tax-id-guide",
    "https://lookuptax.com/docs/es/tax-identification-number/italy-tax-id-guide",
    "https://lookuptax.com/docs/de/tax-identification-number/costa-rica-tax-id-guide",
    "https://lookuptax.com/docs/pt/tax-identification-number/jamaica-tax-id-guide",
    "https://lookuptax.com/docs/zh-Hans/how-to-verify/SIRET-verification-france",
    "https://lookuptax.com/docs/es/tax-identification-number/kuwait-tax-id-guide",
    "https://lookuptax.com/docs/de/tax-identification-number/kuwait-tax-id-guide",
    "https://lookuptax.com/docs/zh-Hans/worldwide-tax-rates",
    "https://lookuptax.com/docs/pt/how-to-verify/rnc-verification-dominican-republic",
    "https://lookuptax.com/docs/zh-Hans/explainers/explaining-OIDAR-services-and-GST-Compliance-for-Suppliers-in-India",
    "https://lookuptax.com/docs/de/tax-identification-number/mexico-tax-id-guide",
    "https://lookuptax.com/docs/es/how-to-verify/registration-number-malaysia",
    "https://lookuptax.com/docs/pt/tax-identification-number/saint-kitts-and-nevis-tax-id-guide",
    "https://lookuptax.com/docs/pt/tax-identification-number/denmark-tax-id-guide",
    "https://lookuptax.com/tag/international-tax",
    "https://lookuptax.com/docs/es/tax-identification-number/denmark-tax-id-guide",
    "https://lookuptax.com/docs/de/tax-identification-number/finland-tax-id-guide",
    "https://lookuptax.com/docs/de/how-to-verify/rut-verification-chile",
    "https://lookuptax.com/docs/es/chaxun-zengzhishui-hao",
    "https://lookuptax.com/docs/chaxun-zengzhishui-hao",
    "https://lookuptax.com/docs/de/chaxun-zengzhishui-hao",
    "https://lookuptax.com/docs/de/tax-identification-number/turkey-tax-id-guide",
    "https://lookuptax.com/docs/es/how-to-verify/qst-verification-canada",
    "https://lookuptax.com/docs/de/tags/cvr",
    "https://lookuptax.com/docs/es/how-to-verify/siren-verification-france",
    "https://lookuptax.com/docs/pt/tax-identification-number/vietnam-tax-id-guide",
    "https://lookuptax.com/docs/de/how-to-verify/qst-verification-canada",
    "https://lookuptax.com/docs/pt/how-to-verify/qst-verification-canada",
    "https://lookuptax.com/docs/pt/tax-identification-number/panama-tax-id-guide",
    "https://lookuptax.com/docs/de/tax-identification-number/panama-tax-id-guide",
    "https://lookuptax.com/docs/es/tax-identification-number/panama-tax-id-guide",
    "https://lookuptax.com/docs/de/blog/guide-to-vat-vies-vat-validation",
    "https://lookuptax.com/docs/de/wie-man-ueberprueft/usa-ein-verifizierung",
    "https://lookuptax.com/docs/de/numero-identificacion-fiscal/guia-rut-uruguay",
    "https://lookuptax.com/docs/zh-Hans/tax-identification-number/mauritius-tax-id-guide",
    "https://lookuptax.com/docs/es/how-to-verify/vat-verification-finland",
    "https://lookuptax.com/docs/pt/explicadores/guia-ioss-importacion",
    "https://lookuptax.com/docs/zh-Hans/how-to-verify/uid-verification-switzerland",
    "https://lookuptax.com/docs/es/how-to-verify/uid-verification-switzerland",
    "https://lookuptax.com/docs/zh-Hans/how-to-verify/rnc-verification-dominican-republic",
    "https://lookuptax.com/docs/es/how-to-verify/dic-verification-czech",
    "https://lookuptax.com/docs/de/how-to-verify/rnc-verification-dominican-republic",
    "https://lookuptax.com/docs/es/numero-identificacao-fiscal/guia-nif-portugal",
    "https://lookuptax.com/docs/es/explainers/KID-number-Norway-kundeidentifikasjon",
    "https://lookuptax.com/docs/de/check-vat-number-free-links-to-official-national-database-search-VAT-number",
    "https://lookuptax.com/tag/e-invoicing",
    "https://lookuptax.com/docs/de/country/france-vat-guidelines-taxe-sur-la-valeur-ajoutée-TVA",
    "https://lookuptax.com/docs/pt/tax-identification-number/israel-tax-id-guide",
    "https://lookuptax.com/docs/es/check-vat-number-free-links-to-official-national-database-search-VAT-number",
    "https://lookuptax.com/docs/pt/como-verificar/verificacion-cpf-brasil",
    "https://lookuptax.com/docs/pt/explainers/KID-number-Norway-kundeidentifikasjon",
    "https://lookuptax.com/docs/de/tags/sst",
    "https://lookuptax.com/docs/pt/tags/iceland",
    "https://lookuptax.com/docs/de/tags/vies",
    "https://lookuptax.com/docs/pt/how-to-verify/find-uen-singapore",
    "https://lookuptax.com/docs/es/tax-identification-number/ghana-tax-id-guide",
    "https://lookuptax.com/docs/zh-Hans/how-to-verify/vatin-verification-onam",
    "https://lookuptax.com/docs/zh-Hans/tax-identification-number/malaysia-tax-id-guide",
    "https://lookuptax.com/docs/zh-Hans/shuiwu-shibie-haoma/yuenan-shuihao",
    "https://lookuptax.com/docs/pt/explainers/Finnish-Reference-number-Finland",
    "https://lookuptax.com/docs/pt/tax-identification-number/seychelles-tax-id-guide",
    "https://lookuptax.com/docs/es/tax-identification-number/poland-tax-id-guide",
    "https://lookuptax.com/docs/es/how-to-verify/dni-verification-argentina",
    "https://lookuptax.com/docs/es/how-to-verify/eori-verification-france",
    "https://lookuptax.com/docs/zh-Hans/tax-identification-number/poland-tax-id-guide",
    "https://lookuptax.com/docs/es/tax-identification-number/greece-tax-id-guide",
    "https://lookuptax.com/docs/de/how-to-verify/tin-zakat-verification-saudi-arabia",
    "https://lookuptax.com/docs/tags/ocr-number",
    "https://lookuptax.com/docs/pt/tax-identification-number/poland-tax-id-guide",
    "https://lookuptax.com/docs/explicadores/directiva-dac7",
    "https://lookuptax.com/docs/pt/tax-identification-number/uzbekistan-tax-id-guide",
    "https://lookuptax.com/docs/es/category/explainers",
    "https://lookuptax.com/docs/de/tax-identification-number/greece-tax-id-guide",
    "https://lookuptax.com/docs/de/how-to-verify/vat-verification-Bosnia",
    "https://lookuptax.com/docs/de/einvoicing/Zatca-fatoora-Saudi-Arabia-einvoicing-zakat-tax-and-customs-authority",
    "https://lookuptax.com/docs/es/blog/tags/lookupapp",
    "https://lookuptax.com/docs/zh-Hans/blog/tags/lookupapp",
    "https://lookuptax.com/docs/zh-Hans/einvoicing/Zatca-fatoora-Saudi-Arabia-einvoicing-zakat-tax-and-customs-authority",
    "https://lookuptax.com/docs/pt/how-to-verify/vatin-verification-onam",
    "https://lookuptax.com/docs/es/ruhe-yanzheng/yingguo-zengzhishui-vat",
    "https://lookuptax.com/docs/tags/china",
    "https://lookuptax.com/docs/how-to-verify/registration-number-malaysia"
)

$results = @()
foreach ($url in $urls) {
    try {
        # Get just the first response (no redirect following)
        $statusLine = & curl.exe -s -o NUL -w "%{http_code}" "$url" 2>&1
        $status = $statusLine.Trim()
        
        # Follow redirects and get final status
        $finalStatusLine = & curl.exe -s -o NUL -w "%{http_code}" -L --max-redirs 10 "$url" 2>&1
        $finalStatus = $finalStatusLine.Trim()
        
        $results += "${status}`t${finalStatus}`t${url}"
    } catch {
        $results += "ERROR`tERROR`t${url}"
    }
}

Write-Output "INITIAL`tFINAL`tURL"
Write-Output "-------`t-----`t---"
$results | ForEach-Object { Write-Output $_ }

# Summary
$non200 = $results | Where-Object { -not $_.StartsWith("301`t200") -and -not $_.StartsWith("200`t200") }
Write-Output ""
Write-Output "=== NON-200 FINAL STATUS ==="
$non200 | ForEach-Object { Write-Output $_ }
